---
- name: Wait for API to return 200
  uri:
    url: "{{kafka_connect_http_protocol}}://{{ansible_host}}:{{kafka_connect_rest_port}}/connectors"
    status_code: 200
    validate_certs: false
  register: result
  until: result.status == 200
  retries: 60
  delay: 10
  when: not rbac_enabled|bool and not kafka_connect_ssl_mutual_auth_enabled|bool

- name: Wait for API to return 200 - mTLS
  uri:
    url: "{{kafka_connect_http_protocol}}://{{inventory_hostname}}:{{kafka_connect_rest_port}}/connectors"
    status_code: 200
    validate_certs: false
    client_cert: "{{kafka_connect_cert_path}}"
    client_key: "{{kafka_connect_key_path}}"
  register: result
  until: result.status == 200
  retries: 60
  delay: 10
  when: not rbac_enabled|bool and kafka_connect_ssl_mutual_auth_enabled|bool

- name: Wait for API to return 200 - RBAC
  uri:
    url: "{{kafka_connect_http_protocol}}://{{ansible_host}}:{{kafka_connect_rest_port}}/connectors"
    status_code: 200
    validate_certs: false
    url_username: "{{kafka_connect_ldap_user}}"
    url_password: "{{kafka_connect_ldap_password}}"
    force_basic_auth: true
  register: result
  until: result.status == 200
  retries: 60
  delay: 10
  when: rbac_enabled|bool and not kafka_connect_ssl_mutual_auth_enabled|bool

- name: Wait for API to return 200 - RBAC - mTLS
  uri:
    url: "{{kafka_connect_http_protocol}}://{{inventory_hostname}}:{{kafka_connect_rest_port}}/connectors"
    status_code: 200
    validate_certs: false
    client_cert: "{{kafka_connect_cert_path}}"
    client_key: "{{kafka_connect_key_path}}"
    url_username: "{{kafka_connect_ldap_user}}"
    url_password: "{{kafka_connect_ldap_password}}"
    force_basic_auth: true
  register: result
  until: result.status == 200
  retries: 60
  delay: 10
  when: rbac_enabled|bool and kafka_connect_ssl_mutual_auth_enabled|bool
