---
lowercaseOutputName: true
lowercaseOutputLabelNames: true
whitelistObjectNames:
- kafka.rest:type=jetty-metrics
- kafka.rest:type=jersey-metrics
rules:
- pattern: 'kafka.rest<type=jetty-metrics>([^:]+):'
  name: "kafka_rest_jetty_metrics_$1"
- pattern: 'kafka.rest<type=jersey-metrics>([^:]+):'
  name: "kafka_rest_jersey_metrics_$1"
