---
- name: Get Principal used on the Inter Broker Listener
  include_tasks: set_principal.yml

# Takes custom super.users and puts into list, without super.users set, should be the empty list []
- name: Initialize Super Users List
  set_fact:
    super_users: "{{ (kafka_broker.properties['super.users'] | default('')).split(';') | difference(['']) }}"

- name: Add each Broker Principal to Super Users List
  set_fact:
    super_users: "{{ super_users }} + [ '{{ hostvars[item]['kafka_broker_principal'] }}' ]"
  loop: "{{ groups['kafka_broker'] }}"

- name: Add MDS Super User to Super Users List
  set_fact:
    super_users: "{{ super_users }} + [ 'User:{{ mds_super_user }}' ]"

- name: Remove Duplicates in Super Users List
  set_fact:
    super_users: "{{ super_users | unique }}"

- name: Add Super Users list to Kafka Properties
  set_fact:
    kafka_broker:
      properties:
        super.users: "{{super_users | join(';')}}"

- name: Create SSL Certificate Directory
  file:
    path: /var/ssl/private
    state: directory
    mode: 0755

- name: Copy in public pem files
  copy:
    src: "{{token_services_public_pem_file}}"
    dest: "{{rbac_enabled_public_pem_path}}"
    mode: '755'
    owner: "{{kafka_broker_user}}"
    group: "{{kafka_broker_group}}"

- name: Copy in private pem files
  copy:
    src: "{{token_services_private_pem_file}}"
    dest: "{{rbac_enabled_private_pem_path}}"
    mode: '755'
    owner: "{{kafka_broker_user}}"
    group: "{{kafka_broker_group}}"
