---
lowercaseOutputName: true
lowercaseOutputLabelNames: true
whitelistObjectNames:
- io.confluent.ksql.metrics:type=ksql-engine-query-stats
rules:
- pattern: 'io.confluent.ksql.metrics<type=ksql-engine-query-stats>([^:]+):'
  name: "ksql_server_metrics_$1"
