---
- name: Wait for webpage to serve content
  uri:
    url: "{{control_center_http_protocol}}://{{ansible_host}}:{{control_center_port}}"
    validate_certs: false
  register: result
  until: result.status == 200
  retries: 60
  delay: 10
  when: not rbac_enabled|bool

- name: Wait for webpage to serve content - RBAC
  uri:
    url: "{{control_center_http_protocol}}://{{ansible_host}}:{{control_center_port}}"
    validate_certs: false
    url_username: "{{control_center_ldap_user}}"
    url_password: "{{control_center_ldap_password}}"
    force_basic_auth: true
  register: result
  until: result.status == 200
  retries: 60
  delay: 10
  when: rbac_enabled|bool
