---
- name: Wait for API to return 200
  uri:
    url: "{{ksql_http_protocol}}://{{ansible_host}}:{{ksql_listener_port}}/info"
    status_code: 200
    validate_certs: false
  register: result
  until: result.status == 200
  retries: 60
  delay: 5
  when: not rbac_enabled|bool

- name: Wait for API to return 200 - RBAC
  uri:
    url: "{{ksql_http_protocol}}://{{ansible_host}}:{{ksql_listener_port}}/info"
    status_code: 200
    validate_certs: false
    url_username: "{{ksql_ldap_user}}"
    url_password: "{{ksql_ldap_password}}"
    force_basic_auth: true
  register: result
  until: result.status == 200
  retries: 60
  delay: 5
  when: rbac_enabled|bool
