---
lowercaseOutputName: true
lowercaseOutputLabelNames: true
rules:
  - pattern : 'kafka.connect<type=app-info, client-id=(.+)><>(.+): (.+)'
    value: 1
    name: kafka_connect_app_info
    labels:
      client-id: $1
      $2: $3
    type: COUNTER
  - pattern : 'kafka.connect<type=connector-metrics, connector=(.+)><>(.+): (.+)'
    value: 1
    name: kafka_connect_connect_connector_metrics
    labels:
      connector: $1
      $2: $3
    type: COUNTER
  - pattern: "kafka.connect<type=connect-worker-metrics>([^:]+):"
    name: "kafka_connect_connect_worker_metrics_$1"
  - pattern: "kafka.connect<type=connect-metrics, client-id=([^:]+)><>([^:]+)"
    name: "kafka_connect_connect_metrics_$1_$2"
  - pattern: "kafka.connect<type=connector-task-metrics, connector=([^:]+), task=([^:]+)><>status: ([^:]+)"
    name: "kafka_connect_connect_connector_metrics"
    value: 1
    labels:
      connector: $1
      task: $2
      status: $3
  - pattern : 'kafka.connect<type=(.+), connector=([^:]+), task=(\d+)><>([^:]+)'
    name: kafka_connect_$1_$4
    labels:
      connector: "$2"
      task: "$3"
  - pattern : 'kafka.connect<type=(.+), connector=([^:]+)><>([^:]+)'
    name: kafka_connect_$1_$3
    labels:
      connector: "$2"