---
# - name: Print some debug information
#   debug: 
#     msg: "{{ msg.split('\n') }}"
#   tags: debug_info 
#   vars: 
#       msg: |
#           {{ hostvars[groups[item] | default(omit) | first] | to_nice_json }}
#   with_items: 
#   - "{{ control_center_metrics_kafka_broker_ansible_group | default([]) }}"
#   - "{{ kafka_broker_cluster_ansible_group_names | default([]) }}"

- name: Setting Host Variables on Secondary Supporting Kafka Cluster Hosts
  set_fact: 
    kafka_broker_rest_proxy_enabled: "{{ hostvars[groups[item] | first].kafka_broker_rest_proxy_enabled | default(_kafka_broker_rest_proxy_enabled) }}"
    rbac_enabled: "{{ hostvars[groups[item] | first].rbac_enabled | default(_rbac_enabled) }}"
    kafka_broker_listeners: "{{ hostvars[groups[item] | first].kafka_broker_listeners | default(_kafka_broker_listeners) }}"
    ssl_enabled: "{{ hostvars[groups[item] | first].ssl_enabled | default(_ssl_enabled) }}"
    pkcs12_enabled: "{{ hostvars[groups[item] | first].pkcs12_enabled | default(_pkcs12_enabled) }}"
    ssl_mutual_auth_enabled: "{{ hostvars[groups[item] | first].ssl_mutual_auth_enabled | default(_ssl_mutual_auth_enabled) }}"
    sasl_protocol: "{{ hostvars[groups[item] | first].sasl_protocol | default(_sasl_protocol) }}"
    sasl_plain_users: "{{ hostvars[groups[item] | first].sasl_plain_users | default(_sasl_plain_users) }}"
    sasl_scram_users: "{{ hostvars[groups[item] | first].sasl_scram_users | default(_sasl_scram_users) }}"
    kerberos_kafka_broker_primary: "{{ hostvars[groups[item] | first].kerberos_kafka_broker_primary | default(_kerberos_kafka_broker_primary) }}"
    mds_bootstrap_server_urls: "{{ hostvars[groups[item] | first].mds_bootstrap_server_urls | default(_mds_bootstrap_server_urls) }}"
    mds_http_protocol: "{{ hostvars[groups[item] | first].mds_http_protocol | default(mds_http_protocol) }}"
    mds_port: "{{ hostvars[groups[item] | first].mds_port | default(_mds_port) }}"
    fips_enabled: "{{ hostvars[groups[item] | first].fips_enabled | default(_fips_enabled) }}"
    kafka_broker_cluster_name: "{{ hostvars[groups[item] | first].kafka_broker_cluster_name | default(_kafka_broker_cluster_name) }}"
    #Kafka Broker Specific Defaults
    kafka_broker_truststore_path:      "{{ hostvars[groups[item] | first].kafka_broker_truststore_path | default(_kafka_broker_truststore_path) }}"
    kafka_broker_truststore_storepass: "{{ hostvars[groups[item] | first].kafka_broker_truststore_storepass | default(_kafka_broker_truststore_storepass) }}"
    kafka_broker_keystore_path:        "{{ hostvars[groups[item] | first].kafka_broker_keystore_path | default(_kafka_broker_keystore_path) }}"
    kafka_broker_keystore_storepass:   "{{ hostvars[groups[item] | first].kafka_broker_keystore_storepass | default(_kafka_broker_keystore_storepass) }}"
    kafka_broker_keystore_keypass:     "{{ hostvars[groups[item] | first].kafka_broker_keystore_keypass | default(_kafka_broker_keystore_keypass) }}"
    kafka_broker_keytab_path:          "{{ hostvars[groups[item] | first].kafka_broker_keytab_path | default(_kafka_broker_keytab_path) }}"
    kafka_broker_kerberos_principal:   "{{ hostvars[groups[item] | first].kafka_broker_kerberos_principal | default(kafka_broker_kerberos_principal)  | default('kafka') }}"
    kafka_broker_ldap_user:            "{{ hostvars[groups[item] | first].kafka_broker_ldap_user | default(_kafka_broker_ldap_user) }}"
    kafka_broker_ldap_password:        "{{ hostvars[groups[item] | first].kafka_broker_ldap_password | default(_kafka_broker_ldap_password) }}"
    #Control Center Specific Defaults. Used in Mutli Kafka Clusters in C3
    control_center_kafka_listener_name:  "{{ hostvars[groups[item] | first].control_center_kafka_listener_name | default(_control_center_kafka_listener_name) }}"
    control_center_truststore_path:      "{{ hostvars[groups[item] | first].control_center_truststore_path | default(_control_center_truststore_path) }}"
    control_center_truststore_storepass: "{{ hostvars[groups[item] | first].control_center_truststore_storepass | default(_control_center_truststore_storepass) }}"
    control_center_keystore_path:        "{{ hostvars[groups[item] | first].control_center_keystore_path | default(_control_center_keystore_path) }}"
    control_center_keystore_storepass:   "{{ hostvars[groups[item] | first].control_center_keystore_storepass | default(_control_center_keystore_storepass) }}"
    control_center_keystore_keypass:     "{{ hostvars[groups[item] | first].control_center_keystore_keypass | default(_control_center_keystore_keypass) }}"
    control_center_keytab_path:          "{{ hostvars[groups[item] | first].control_center_keytab_path | default(_control_center_keytab_path) }}"
    control_center_kerberos_principal:   "{{ hostvars[groups[item] | first].control_center_kerberos_principal | default(control_center_kerberos_principal)  | default('c3') }}"
    control_center_ldap_user:            "{{ hostvars[groups[item] | first].control_center_ldap_user | default(_control_center_ldap_user) }}"
    control_center_ldap_password:        "{{ hostvars[groups[item] | first].control_center_ldap_password | default(_control_center_ldap_password) }}"
  delegate_to: "{{ groups[item] | first }}"
  delegate_facts: true
  when: groups[item] | default(omit) | length > 0
  with_items: 
  - "{{ control_center_metrics_kafka_broker_ansible_group | default([]) }}"
  - "{{ kafka_broker_cluster_ansible_group_names | default([]) }}"
  run_once: true

# - name: Print some debug information
#   debug: 
#     msg: "{{ msg.split('\n') }}"
#   tags: debug_info 
#   vars: 
#       msg: |
#           {{ hostvars[groups[item] | default(omit) | first] | to_nice_json }}
#   with_items: 
#   - "{{ control_center_metrics_kafka_broker_ansible_group | default([]) }}"
#   - "{{ kafka_broker_cluster_ansible_group_names | default([]) }}"